apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - github.com/kubeflow/manifests/contrib/kserve/kserve
  - github.com/kubeflow/manifests/contrib/kserve/models-web-app/overlays/kubeflow
