pipelines:
  config:
    db:
      user:
        secretKeyRef:
          name: db-credentials
      password:
        secretKeyRef:
          name: db-credentials
          key: mysql-root-password
      host:
        secretKeyRef:
          name: db-credentials
    objectStore:
      accessKey:
        secretKeyRef:
          name: mlpipeline-minio-artifact
      secretAccessKey:
        secretKeyRef:
          name: mlpipeline-minio-artifact
